language: ruby
os: osx
env: OSX=10.12
osx_image: xcode8.1
rvm: system

before_install:
  - brew tap rockyluke/devops

install:
  - brew install i2cssh
  - brew install puppet-lint
  - brew install rubocop

script:
  - brew doctor

notifications:
  email:
    on_success: never
    on_failure: always
